"""add phone number

Revision ID: 5e8d3aceffc7
Revises: e9a068574599
Create Date: 2026-09-26 20:18:30.592453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8d3aceffc7'
down_revision: Union[str, Sequence[str], None] = 'e9a068574599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('phone_number', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'phone_number')
    # ### end Alembic commands ###
